### ISSUE TITLE
Having the "style" twice seems redundant

### ISSUE THREAD

**Issue by elken** [cjohansen/phosphor-clj#1]
Looks like you saved me again :P Was on the verge of building my own version of something like this, so thanks!

I just got tripped up with `:phosphor.fill/list` being invalid and requiring `fill` twice as `:phosphor.fill/list-fill`. Having it twice seems redundant to me, would it be simple to remove the trailing one? To me `:phosphor.fill/list` is the best version here.

**Comment by cjohansen** [comment]
Ah, I hadn't noticed the double style. I agree that it's enough to have it once in the namespace, will fix.

**Comment by cjohansen** [comment]
Fixed in 2023.04.25 👍
